"""Initial authenticated LocalSignal schema."""
from alembic import op
import sqlalchemy as sa
revision="0001_initial_schema";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("email",sa.String(240),nullable=False),sa.Column("password_hash",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("email"));op.create_index("ix_users_email","users",["email"])
 op.create_table("businesses",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("website",sa.String(500),nullable=False),sa.Column("industry",sa.String(120),nullable=False),sa.Column("city",sa.String(160),nullable=False),sa.Column("country",sa.String(100),nullable=False),sa.Column("created_at",sa.DateTime(),server_default=sa.func.now(),nullable=False));op.create_index("ix_businesses_user_id","businesses",["user_id"]);op.create_index("ix_businesses_name","businesses",["name"])
 for name,columns in [("competitors",[sa.Column("name",sa.String(160),nullable=False),sa.Column("website",sa.String(500),nullable=False),sa.Column("category",sa.String(120),nullable=False),sa.Column("location",sa.String(160),nullable=False),sa.Column("rating",sa.Float(),nullable=False),sa.Column("reviews",sa.Integer(),nullable=False)]),("keywords",[sa.Column("keyword",sa.String(240),nullable=False),sa.Column("location",sa.String(160),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("previous",sa.Integer(),nullable=False),sa.Column("volume",sa.Integer(),nullable=False)]),("reviews",[sa.Column("customer",sa.String(120),nullable=False),sa.Column("source",sa.String(60),nullable=False),sa.Column("rating",sa.Integer(),nullable=False),sa.Column("review_date",sa.Date(),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("theme",sa.String(80),nullable=False),sa.Column("sentiment",sa.String(20),nullable=False)])]:
  op.create_table(name,sa.Column("id",sa.Integer(),primary_key=True),sa.Column("business_id",sa.Integer(),sa.ForeignKey("businesses.id",ondelete="CASCADE"),nullable=False),*columns);op.create_index(f"ix_{name}_business_id",name,["business_id"])
 op.create_index("ix_keywords_keyword","keywords",["keyword"])
def downgrade():
 op.drop_table("reviews");op.drop_table("keywords");op.drop_table("competitors");op.drop_table("businesses");op.drop_table("users")
