import { useMemo, useState } from 'react'
import { Filter, MessageSquare, Plus, Search, Star, Trash2, TrendingUp, X } from 'lucide-react'
import './reviews.css'
import './api-state.css'
import { ApiState, useApiCollection } from './useApiCollection'

type Sentiment='Positive'|'Neutral'|'Negative'
type Review={id:string;customer:string;source:string;rating:number;date:string;text:string;theme:string;sentiment:Sentiment}
const samples:Review[]=[
 {id:'r1',customer:'Angela M.',source:'Google',rating:5,date:'2026-09-05',text:'The team arrived on time and communicated clearly throughout the service.',theme:'Reliability',sentiment:'Positive'},
 {id:'r2',customer:'David R.',source:'Google',rating:4,date:'2026-08-29',text:'Professional service and a good result. Scheduling took a little longer than expected.',theme:'Professionalism',sentiment:'Positive'},
 {id:'r3',customer:'Monica T.',source:'Facebook',rating:3,date:'2026-08-21',text:'The service was fine, but I had to follow up twice before receiving a response.',theme:'Communication',sentiment:'Neutral'},
 {id:'r4',customer:'James K.',source:'Google',rating:2,date:'2026-08-14',text:'The appointment started late and the billing details were unclear.',theme:'Timeliness',sentiment:'Negative'}
]
const blank={customer:'',source:'Google',rating:5,date:new Date().toISOString().slice(0,10),text:'',theme:'Professionalism',sentiment:'Positive' as Sentiment}

export default function ReviewsPage(){
 const {items,connected,save,remove}=useApiCollection<Review>('reviews','localsignal-reviews',samples,x=>({customer:x.customer,source:x.source,rating:x.rating,review_date:x.date,text:x.text,theme:x.theme,sentiment:x.sentiment}),row=>({...row,id:String(row.id),date:row.review_date}))
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[open,setOpen]=useState(false),[form,setForm]=useState(blank)
 const saveItems=(next:Review[])=>{const deleted=items.find(x=>!next.some(n=>n.id===x.id));if(deleted)remove(deleted.id)}
 const filtered=useMemo(()=>items.filter(x=>(filter==='All'||x.sentiment===filter)&&[x.customer,x.text,x.theme,x.source].join(' ').toLowerCase().includes(query.toLowerCase())),[items,query,filter])
 const average=items.length?(items.reduce((n,x)=>n+x.rating,0)/items.length).toFixed(1):'0.0'
 const positive=items.length?Math.round(items.filter(x=>x.sentiment==='Positive').length/items.length*100):0
 const themes=Object.entries(items.reduce<Record<string,number>>((a,x)=>(a[x.theme]=(a[x.theme]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();await save(form);setOpen(false);setForm(blank)}
 return <>
  <header><div><h1>Reviews and reputation</h1><p>Understand what customers value, where concerns appear, and how reputation changes.<ApiState connected={connected}/></p></div><button className="primary page-button" onClick={()=>setOpen(true)}><Plus size={16}/>Add review</button></header>
  <section className="review-stats"><article><span><Star/></span><div><small>Average rating</small><b>{average}</b></div></article><article><span><MessageSquare/></span><div><small>Reviews analyzed</small><b>{items.length}</b></div></article><article><span><TrendingUp/></span><div><small>Positive sentiment</small><b>{positive}%</b></div></article><article><span><Filter/></span><div><small>Leading theme</small><b>{themes[0]?.[0]||'—'}</b></div></article></section>
  <section className="review-grid"><article className="panel reviews-list"><div className="review-toolbar"><div><h2>Customer reviews</h2><p>Search and filter the evidence behind your reputation score.</p></div><div className="review-controls"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reviews"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Positive</option><option>Neutral</option><option>Negative</option></select></div></div>
   <div className="review-items">{filtered.length?filtered.map(item=><div className="review-item" key={item.id}><div className="review-avatar">{item.customer.slice(0,1).toUpperCase()}</div><div className="review-copy"><div className="review-title"><b>{item.customer}</b><span>{item.source} · {new Date(item.date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span><button onClick={()=>{if(confirm('Remove this review?'))saveItems(items.filter(x=>x.id!==item.id))}} aria-label="Delete review"><Trash2/></button></div><div className="review-rating">{[1,2,3,4,5].map(n=><Star key={n} className={n<=item.rating?'filled':''} fill={n<=item.rating?'currentColor':'none'}/>)}</div><p>{item.text}</p><div className="review-tags"><span>{item.theme}</span><span className={item.sentiment.toLowerCase()}>{item.sentiment}</span></div></div></div>):<div className="review-empty"><Search/><h2>No reviews match</h2><p>Change the filter or add a review.</p></div>}</div>
  </article><aside className="review-side"><article className="panel"><span className="eyebrow muted">CUSTOMER THEMES</span><h2>What people mention</h2><div className="themes">{themes.map(([name,count])=><div key={name}><span>{name}</span><b>{Math.round(count/items.length*100)}%</b><i><em style={{width:`${count/items.length*100}%`}}/></i></div>)}</div></article><article className="panel reputation-insight"><span><TrendingUp/></span><small>REPUTATION INSIGHT</small><h2>Communication needs attention</h2><p>Customer feedback mentioning communication is less positive than your leading themes. Review response time and follow up procedures.</p></article></aside></section>
  {open&&<div className="modal-backdrop"><form className="modal review-form" onSubmit={submit}><div className="modal-top"><div><h2>Add a customer review</h2><p>Enter only feedback you are permitted to analyze.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label>Customer name<input required value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})} placeholder="Name or initials"/></label><label>Source<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option>Google</option><option>Facebook</option><option>Yelp</option><option>Website</option><option>Other</option></select></label><label>Rating<select value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label><label>Review date<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Theme<select value={form.theme} onChange={e=>setForm({...form,theme:e.target.value})}><option>Professionalism</option><option>Customer service</option><option>Quality</option><option>Reliability</option><option>Communication</option><option>Timeliness</option><option>Price</option><option>Billing</option></select></label><label>Sentiment<select value={form.sentiment} onChange={e=>setForm({...form,sentiment:e.target.value as Sentiment})}><option>Positive</option><option>Neutral</option><option>Negative</option></select></label><label className="wide">Review text<textarea required value={form.text} onChange={e=>setForm({...form,text:e.target.value})} placeholder="Paste or type the review text"/></label></div><div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" type="submit">Analyze review</button></div></form></div>}
 </>
}
